language: node_js

node_js:
  - 10.14.1

cache:
  directories:
  - node_modules

before_install:
  - sudo apt-get install -y sshpass

script:
  - npm install
  - npm run lint
  - npm run build

branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
